"""add meal_type to food_logs

Revision ID: 38fd9abf7399
Revises: f2c3a8d9e1f4
Create Date: 2026-04-08 12:35:10.373284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38fd9abf7399'
down_revision: Union[str, None] = 'f2c3a8d9e1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_logs', sa.Column('meal_type', sa.String(length=20), nullable=True))
    op.alter_column('nutrition_kb', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('nutrition_kb_embedding_idx'), table_name='nutrition_kb', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('nutrition_kb_embedding_idx'), 'nutrition_kb', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('nutrition_kb', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('food_logs', 'meal_type')
    # ### end Alembic commands ###
