"""add health profile fields

Revision ID: d76db7f96f20
Revises: 38fd9abf7399
Create Date: 2026-06-13 20:43:13.352438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76db7f96f20'
down_revision: Union[str, None] = '38fd9abf7399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('race', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('goal', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('medical_conditions', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('surgeries', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('medications', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'medications')
    op.drop_column('user_profiles', 'surgeries')
    op.drop_column('user_profiles', 'medical_conditions')
    op.drop_column('user_profiles', 'goal')
    op.drop_column('user_profiles', 'race')
    # ### end Alembic commands ###
